# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20190722_0412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animals',
        ),
        migrations.DeleteModel(
            name='Architecture',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Landscapes',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
