# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_animals_architecture_food_landscapes_sport_travel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animals',
            old_name='image',
            new_name='animal',
        ),
        migrations.RenameField(
            model_name='architecture',
            old_name='image',
            new_name='architecture',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='image',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='landscapes',
            old_name='image',
            new_name='landscape',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='image',
            new_name='sport',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='image',
            new_name='travel',
        ),
    ]
