# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20190722_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='image_url',
            field=models.CharField(default='image.jpg', max_length=250),
        ),
        migrations.AddField(
            model_name='architecture',
            name='image_url',
            field=models.CharField(default='image.jpg', max_length=250),
        ),
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.CharField(default='image.jpg', max_length=250),
        ),
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.CharField(default='image.jpg', max_length=250),
        ),
        migrations.AddField(
            model_name='landscapes',
            name='image_url',
            field=models.CharField(default='image.jpg', max_length=250),
        ),
        migrations.AddField(
            model_name='sport',
            name='image_url',
            field=models.CharField(default='image.jpg', max_length=250),
        ),
        migrations.AddField(
            model_name='travel',
            name='image_url',
            field=models.CharField(default='image.jpg', max_length=250),
        ),
    ]
